In [1]:
import requests
import re
from bs4 import BeautifulSoup
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

In [10]:
headers={"User-Agent":"Mozilla/5.0"}
url="https://www.flipkart.com/search?q=laptops&as=on&as-show=on&otracker=AS_Query_TrendingAutoSuggest_5_0_na_na_na&otracker1=AS_Query_TrendingAutoSuggest_5_0_na_na_na&as-pos=5&as-type=TRENDING&suggestionId=laptops&requestId=8809d76a-c51d-49f1-b6a9-23641fb8f697"

In [11]:
response = requests.get(url,headers=headers)

In [12]:
print(response.status_code)

200

In [14]:
soup=BeautifulSoup(response.content,"html.parser")
print(soup)

<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css" rel="stylesheet"/><meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.fbae9b38.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.2ac7a93e.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.6a960ee6.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.1b037c04.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.4f62c21c.js"></script> <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css" rel="stylesheet"/><title>Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta content="Laptops- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"><meta content="Laptops" name="Keywords"> <meta content="Laptops- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"><meta content="Laptops- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"> <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"> <!--[if IE 9 ]>
	<script nonce="800209956103968851">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="800209956103968851">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <script nonce="800209956103968851">;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

### Extract Brand

In [15]:
soup.find_all("div",class_="RG5Slk")

[<div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...</div>,
 <div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-L...</div>,
 <div class="RG5Slk">Acer Aspire 15 MS Office 2024 + M365 Basic, AMD Ryzen 3 Quad Core 7330U - (8 GB/256 GB SSD/Windows 11 ...</div>,
 <div class="RG5Slk">Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home) AL15-52H Noteb...</div>,
 <div class="RG5Slk">ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic* Intel Core i3 13th Gen - (8 GB/512 GB SSD/Windo...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U - (16 GB/512 GB SSD/Windows 11 Home) NP750XHD Th...</div>,
 <div class="RG5Slk">walker Intel Celeron Dual Core Intel N4020 - (4 GB/128 GB SSD/Windows 11 Home) NU14A2 Thin and Light L...</div>,
 <div class="RG5Slk">MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus - (32 GB/512 GB SSD/Windows 11 Home) EP2-59193 L...</div>,
 <div class="RG5Slk">Acer One 14 AMD Ryzen 3 Quad Core 7320U - (8 GB/256 GB SSD/Windows 11 Home) A114-43 Thin and Light Lap...</div>,
 <div class="RG5Slk">Acer Aspire 3 Intel Pentium Quad Core N6000 - (12 GB/512 GB SSD/Windows 11 Home) A325-45 Thin and Ligh...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (16 GB/512 GB SSD/Windows 11 Home) NP750XHD Th...</div>,
 <div class="RG5Slk">Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home) 15IRH8 Thin a...</div>,
 <div class="RG5Slk">ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X - (16 GB/512 GB...</div>,
 <div class="RG5Slk">MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite - (16 GB/512 GB SSD/Windows 11 Home) EP2-60196 La...</div>,
 <div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...</div>,
 <div class="RG5Slk">Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (32 GB/1 TB SSD/Windows 11 Home) NP750XHD Thin...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (16 GB/1 TB SSD/Windows 11 Home) NP750XHD Thin...</div>,
 <div class="RG5Slk">ASUS ROG Zephyrus G16 OLED (2026) Intel Core Ultra 9 386H - (32 GB/2 TB SSD/Windows 11 Home/12 GB Grap...</div>,
 <div class="RG5Slk">Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781) - (8 GB/256 GB/Android 15) PBG9915256#4...</div>,
 <div class="RG5Slk">ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H - (32 GB/512 GB SSD/Windows 11 Home) P1403CVA-S60940W...</div>,
 <div class="RG5Slk">ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U - (8 GB/512 GB SSD/Windows 1...</div>,
 <div class="RG5Slk">MSI Modern 14 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) 14 C13M-115IN / 14 C13M...</div>,
 <div class="RG5Slk">Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U - (8 GB/256 GB SSD/Windows 11 Home) AS15-42 Thin and Light L...</div>]

In [16]:
a=soup.find_all("div",class_="RG5Slk")[0].text
a

'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...'

In [17]:
re.findall(r"(.+)\s\-",a)

['Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U']

In [18]:
brand=[]
for tag in soup.find_all("div",class_="RG5Slk"):
    text=tag.text
    a=re.findall(r"(.+)\s\-",text)
    brand.extend(a)
brand

['Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
 'Acer Aspire 15 MS Office 2024 + M365 Basic, AMD Ryzen 3 Quad Core 7330U',
 'Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 210H',
 'ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic* Intel Core i3 13th Gen',
 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
 'walker Intel Celeron Dual Core Intel N4020',
 'MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus',
 'Acer One 14 AMD Ryzen 3 Quad Core 7320U',
 'Acer Aspire 3 Intel Pentium Quad Core N6000',
 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H',
 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X',
 'MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite',
 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
 'Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H',
 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
 'ASUS ROG Zephyrus G16 OLED (2026) Intel Core Ultra 9 386H',
 'Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781)',
 'ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H',
 'ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U',
 'MSI Modern 14 Intel Core i3 13th Gen 1315U',
 'Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U']

### Extracting the Brand_title

In [19]:
soup.find_all("div",class_="RG5Slk")

[<div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...</div>,
 <div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-L...</div>,
 <div class="RG5Slk">Acer Aspire 15 MS Office 2024 + M365 Basic, AMD Ryzen 3 Quad Core 7330U - (8 GB/256 GB SSD/Windows 11 ...</div>,
 <div class="RG5Slk">Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 210H - (16 GB/512 GB SSD/Windows 11 Home) AL15-52H Noteb...</div>,
 <div class="RG5Slk">ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic* Intel Core i3 13th Gen - (8 GB/512 GB SSD/Windo...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U - (16 GB/512 GB SSD/Windows 11 Home) NP750XHD Th...</div>,
 <div class="RG5Slk">walker Intel Celeron Dual Core Intel N4020 - (4 GB/128 GB SSD/Windows 11 Home) NU14A2 Thin and Light L...</div>,
 <div class="RG5Slk">MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus - (32 GB/512 GB SSD/Windows 11 Home) EP2-59193 L...</div>,
 <div class="RG5Slk">Acer One 14 AMD Ryzen 3 Quad Core 7320U - (8 GB/256 GB SSD/Windows 11 Home) A114-43 Thin and Light Lap...</div>,
 <div class="RG5Slk">Acer Aspire 3 Intel Pentium Quad Core N6000 - (12 GB/512 GB SSD/Windows 11 Home) A325-45 Thin and Ligh...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (16 GB/512 GB SSD/Windows 11 Home) NP750XHD Th...</div>,
 <div class="RG5Slk">Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD/Windows 11 Home) 15IRH8 Thin a...</div>,
 <div class="RG5Slk">ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X - (16 GB/512 GB...</div>,
 <div class="RG5Slk">MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite - (16 GB/512 GB SSD/Windows 11 Home) EP2-60196 La...</div>,
 <div class="RG5Slk">Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...</div>,
 <div class="RG5Slk">Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (32 GB/1 TB SSD/Windows 11 Home) NP750XHD Thin...</div>,
 <div class="RG5Slk">Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U - (16 GB/1 TB SSD/Windows 11 Home) NP750XHD Thin...</div>,
 <div class="RG5Slk">ASUS ROG Zephyrus G16 OLED (2026) Intel Core Ultra 9 386H - (32 GB/2 TB SSD/Windows 11 Home/12 GB Grap...</div>,
 <div class="RG5Slk">Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781) - (8 GB/256 GB/Android 15) PBG9915256#4...</div>,
 <div class="RG5Slk">ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H - (32 GB/512 GB SSD/Windows 11 Home) P1403CVA-S60940W...</div>,
 <div class="RG5Slk">ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U - (8 GB/512 GB SSD/Windows 1...</div>,
 <div class="RG5Slk">MSI Modern 14 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) 14 C13M-115IN / 14 C13M...</div>,
 <div class="RG5Slk">Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U - (8 GB/256 GB SSD/Windows 11 Home) AS15-42 Thin and Light L...</div>]

In [20]:
a=soup.find_all("div",class_="RG5Slk")[0].text
a

'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-K...'

In [21]:
re.findall(r"^[A-Za-z]+", a)

['Samsung']

In [22]:
Brand_title=[]
for tag in soup.find_all("div",class_="RG5Slk"):
    text=tag.text
    a= re.findall(r"^[A-Za-z]+", text)
    Brand_title.extend(a)
Brand_title

['Samsung',
 'Samsung',
 'Acer',
 'Acer',
 'ASUS',
 'Samsung',
 'walker',
 'MICROSOFT',
 'Acer',
 'Acer',
 'Samsung',
 'Lenovo',
 'ASUS',
 'MICROSOFT',
 'Samsung',
 'Acer',
 'Samsung',
 'Samsung',
 'ASUS',
 'Primebook',
 'ASUS',
 'ASUS',
 'MSI',
 'Acer']

### Extracting the  Processor

In [23]:
a=soup.find_all("li",class_="DTBslk")
a

[<li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">MSO</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 + Microsoft 365 Basic</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Celeron Dual Core Processor</li>,
 <li class="DTBslk">4 GB DDR4 RAM</li>,
 <li class="DTBslk">32 bit Windows 11 Operating System</li>,
 <li class="DTBslk">128 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Snapdragon X2 Plus Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.05 cm (13.8 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Pentium Quad Core Processor</li>,
 <li class="DTBslk">12 GB LPDDR4X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Yr. Onsite + 1 Yr. Accidental Damage Protection</li>,
 <li class="DTBslk">Snapdragon X Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Snapdragon X2 Elite Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">38.1 cm (15 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core 7 Processor</li>,
 <li class="DTBslk">16 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 9 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">2 TB SSD</li>,
 <li class="DTBslk">40.64 cm (16 inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic with 100GB Cloud Storage for 1 Year, McAfee 1 year, Xbox Game Pass for 2 months</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">MediaTek Helio G99 (MT8781) Processor</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Android Operating System</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core i7 Processor (13th Gen)</li>,
 <li class="DTBslk">32 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core 3 Processor (14th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Limited Warranty</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Carry-in Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>]

In [24]:
a=soup.find_all("li",class_="DTBslk")[0].text
a

'Intel Core i5 Processor (13th Gen)'

In [25]:
processor=[]
for tag in soup.find_all("li",class_="DTBslk"):
    text=tag.text
    a=re.findall(r"(.+)",text)
    processor.extend(a)
processor

['Intel Core i5 Processor (13th Gen)',
 '8 GB LPDDR4X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Core i3 Processor (13th Gen)',
 '8 GB LPDDR4X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Year Onsite Warranty',
 'AMD Ryzen 3 Quad Core Processor',
 '8 GB DDR4 RAM',
 '64 bit Windows 11 Home Operating System',
 '256 GB SSD',
 '39.62 cm (15.6 inch) Display',
 'MSO',
 '1 Year Onsite Service',
 'Intel Core 5 Processor',
 '16 GB LPDDR5 RAM',
 '64 bit Windows 11 Home Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 inch) Display',
 '1 Year Onsite Service',
 'Intel Core i3 Processor (13th Gen)',
 '8 GB DDR5 RAM',
 'Windows 11 Home Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 'Microsoft Office Home 2024 + Microsoft 365 Basic',
 '1 Year Onsite Warranty',
 'Intel Core Ultra 5 Processor',
 '16 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 'MS Office Home and Student 2024',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Celeron Dual Core Processor',
 '4 GB DDR4 RAM',
 '32 bit Windows 11 Operating System',
 '128 GB SSD',
 '35.56 cm (14 inch) Display',
 '1 Year Onsite Service',
 'Snapdragon X2 Plus Processor',
 '32 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '35.05 cm (13.8 inch) Touchscreen Display',
 'NA',
 '1 Year Onsite Service',
 'AMD Ryzen 3 Quad Core Processor',
 '8 GB LPDDR5 RAM',
 '64 bit Windows 11 Operating System',
 '256 GB SSD',
 '35.56 cm (14 Inch) Display',
 '1 Year International Travelers Warranty (ITW)',
 'Intel Pentium Quad Core Processor',
 '12 GB LPDDR4X RAM',
 'Windows 11 Home Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Year International Travelers Warranty (ITW)',
 'Intel Core Ultra 7 Processor',
 '16 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 'MS Office Home and Student 2024',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Core i5 Processor (13th Gen)',
 '16 GB LPDDR5 RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Yr. Onsite + 1 Yr. Accidental Damage Protection',
 'Snapdragon X Processor',
 '16 GB LPDDR5X RAM',
 'Windows 11 Home Operating System',
 '512 GB SSD',
 '35.56 cm (14 Inch) Display',
 'Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps',
 '1 Year Onsite Warranty',
 'Snapdragon X2 Elite Processor',
 '16 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '38.1 cm (15 inch) Touchscreen Display',
 'NA',
 '1 Year Onsite Service',
 'Intel Core i5 Processor (13th Gen)',
 '8 GB LPDDR4X RAM',
 '64 bit Windows 11 Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Core 7 Processor',
 '16 GB DDR4 RAM',
 '64 bit Windows 11 Home Operating System',
 '512 GB SSD',
 '39.62 cm (15.6 Inch) Display',
 '1 Year Warranty',
 'Intel Core Ultra 7 Processor',
 '32 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '1 TB SSD',
 '39.62 cm (15.6 Inch) Display',
 'MS Office Home and Student 2024',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Core Ultra 7 Processor',
 '16 GB LPDDR5X RAM',
 '64 bit Windows 11 Operating System',
 '1 TB SSD',
 '39.62 cm (15.6 Inch) Display',
 'MS Office Home and Student 2024',
 '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
 'Intel Core Ultra 9 Processor',
 '32 GB LPDDR5X RAM',
 'Windows 11 Home Operating System',
 '2 TB SSD',
 '40.64 cm (16 inch) Display',
 'Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic with 100GB Cloud Storage for 1 Year, McAfee 1 year, Xbox Game Pass for 2 months',
 '1 Year Onsite Service',
 'MediaTek Helio G99 (MT8781) Processor',
 '8 GB LPDDR4X RAM',
 '64 bit Android Operating System',
 '39.62 cm (15.6 Inch) Display',
 '1 Year Onsite Warranty',
 'Intel Core i7 Processor (13th Gen)',
 '32 GB DDR5 RAM',
 '64 bit Windows 11 Home Operating System',
 '512 GB SSD',
 '35.56 cm (14 Inch) Display',
 'Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)',
 '1 Year Onsite Warranty',
 'Intel Core 3 Processor (14th Gen)',
 '8 GB DDR5 RAM',
 '64 bit Windows 11 Home Operating System',
 '512 GB SSD',
 '35.56 cm (14 Inch) Display',
 '1 Year Limited Warranty',
 'Intel Core i3 Processor (13th Gen)',
 '8 GB DDR4 RAM',
 'Windows 11 Operating System',
 '512 GB SSD',
 '35.56 cm (14 Inch) Display',
 '1 Year Carry-in Warranty',
 'AMD Ryzen 3 Quad Core Processor',
 '8 GB DDR4 RAM',
 'Windows 11 Operating System',
 '256 GB SSD',
 '39.62 cm (15.6 inch) Display',
 '1 Year Onsite Warranty']

### Extracting RAM

In [26]:
a=soup.find_all("li",class_="DTBslk")
a

[<li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">MSO</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 + Microsoft 365 Basic</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Celeron Dual Core Processor</li>,
 <li class="DTBslk">4 GB DDR4 RAM</li>,
 <li class="DTBslk">32 bit Windows 11 Operating System</li>,
 <li class="DTBslk">128 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Snapdragon X2 Plus Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.05 cm (13.8 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Pentium Quad Core Processor</li>,
 <li class="DTBslk">12 GB LPDDR4X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Yr. Onsite + 1 Yr. Accidental Damage Protection</li>,
 <li class="DTBslk">Snapdragon X Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Snapdragon X2 Elite Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">38.1 cm (15 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core 7 Processor</li>,
 <li class="DTBslk">16 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 9 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">2 TB SSD</li>,
 <li class="DTBslk">40.64 cm (16 inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic with 100GB Cloud Storage for 1 Year, McAfee 1 year, Xbox Game Pass for 2 months</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">MediaTek Helio G99 (MT8781) Processor</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Android Operating System</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core i7 Processor (13th Gen)</li>,
 <li class="DTBslk">32 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core 3 Processor (14th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Limited Warranty</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Carry-in Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>]

In [27]:
a=soup.find_all("li",class_="DTBslk")[1].text
a

'8 GB LPDDR4X RAM'

In [28]:
ram=[]
for tag in soup.find_all("li",class_="DTBslk"):
    text=tag.text
    a=re.findall(r"(\d+).+RAM",text)
    ram.extend(a)

ram

['8',
 '8',
 '8',
 '16',
 '8',
 '16',
 '4',
 '32',
 '8',
 '12',
 '16',
 '16',
 '16',
 '16',
 '8',
 '16',
 '32',
 '16',
 '32',
 '8',
 '32',
 '8',
 '8',
 '8']

### Extracting SSD

In [29]:
a=soup.find_all("li",class_="DTBslk")
a

[<li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">MSO</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 + Microsoft 365 Basic</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Celeron Dual Core Processor</li>,
 <li class="DTBslk">4 GB DDR4 RAM</li>,
 <li class="DTBslk">32 bit Windows 11 Operating System</li>,
 <li class="DTBslk">128 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Snapdragon X2 Plus Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.05 cm (13.8 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Pentium Quad Core Processor</li>,
 <li class="DTBslk">12 GB LPDDR4X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Yr. Onsite + 1 Yr. Accidental Damage Protection</li>,
 <li class="DTBslk">Snapdragon X Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Snapdragon X2 Elite Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">38.1 cm (15 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core 7 Processor</li>,
 <li class="DTBslk">16 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 9 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">2 TB SSD</li>,
 <li class="DTBslk">40.64 cm (16 inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic with 100GB Cloud Storage for 1 Year, McAfee 1 year, Xbox Game Pass for 2 months</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">MediaTek Helio G99 (MT8781) Processor</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Android Operating System</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core i7 Processor (13th Gen)</li>,
 <li class="DTBslk">32 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core 3 Processor (14th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Limited Warranty</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Carry-in Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>]

In [30]:
a=soup.find_all("li",class_="DTBslk")[3].text
a

'512 GB SSD'

In [31]:
ssd=[]
for tag in soup.find_all("li",class_="DTBslk"):
    text=tag.text
    a=re.findall(r"(\d+)\s.+",text)
    ssd.extend(a)
ssd

['5',
 '8',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '64',
 '256',
 '62',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '11',
 '512',
 '62',
 '2024',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '4',
 '32',
 '128',
 '56',
 '1',
 '2',
 '32',
 '64',
 '512',
 '05',
 '1',
 '3',
 '8',
 '64',
 '256',
 '56',
 '1',
 '12',
 '11',
 '512',
 '62',
 '1',
 '7',
 '16',
 '64',
 '512',
 '62',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '16',
 '11',
 '512',
 '56',
 '2024',
 '1',
 '2',
 '16',
 '64',
 '512',
 '1',
 '1',
 '5',
 '8',
 '64',
 '512',
 '62',
 '1',
 '7',
 '16',
 '64',
 '512',
 '62',
 '1',
 '7',
 '32',
 '64',
 '1',
 '62',
 '1',
 '7',
 '16',
 '64',
 '1',
 '62',
 '1',
 '9',
 '32',
 '11',
 '2',
 '64',
 '2024',
 '1',
 '99',
 '8',
 '64',
 '62',
 '1',
 '7',
 '32',
 '64',
 '512',
 '56',
 '365',
 '1',
 '3',
 '8',
 '64',
 '512',
 '56',
 '1',
 '3',
 '8',
 '11',
 '512',
 '56',
 '1',
 '3',
 '8',
 '11',
 '256',
 '62',
 '1']

### Extracting Display

In [32]:
a=soup.find_all("li",class_="DTBslk")
a

[<li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">MSO</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 + Microsoft 365 Basic</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 5 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Celeron Dual Core Processor</li>,
 <li class="DTBslk">4 GB DDR4 RAM</li>,
 <li class="DTBslk">32 bit Windows 11 Operating System</li>,
 <li class="DTBslk">128 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Snapdragon X2 Plus Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.05 cm (13.8 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Pentium Quad Core Processor</li>,
 <li class="DTBslk">12 GB LPDDR4X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year International Travelers Warranty (ITW)</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">16 GB LPDDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Yr. Onsite + 1 Yr. Accidental Damage Protection</li>,
 <li class="DTBslk">Snapdragon X Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Snapdragon X2 Elite Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">38.1 cm (15 inch) Touchscreen Display</li>,
 <li class="DTBslk">NA</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">Intel Core i5 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core 7 Processor</li>,
 <li class="DTBslk">16 GB DDR4 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Warranty</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 7 Processor</li>,
 <li class="DTBslk">16 GB LPDDR5X RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Operating System</li>,
 <li class="DTBslk">1 TB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">MS Office Home and Student 2024</li>,
 <li class="DTBslk">1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories</li>,
 <li class="DTBslk">Intel Core Ultra 9 Processor</li>,
 <li class="DTBslk">32 GB LPDDR5X RAM</li>,
 <li class="DTBslk">Windows 11 Home Operating System</li>,
 <li class="DTBslk">2 TB SSD</li>,
 <li class="DTBslk">40.64 cm (16 inch) Display</li>,
 <li class="DTBslk">Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic with 100GB Cloud Storage for 1 Year, McAfee 1 year, Xbox Game Pass for 2 months</li>,
 <li class="DTBslk">1 Year Onsite Service</li>,
 <li class="DTBslk">MediaTek Helio G99 (MT8781) Processor</li>,
 <li class="DTBslk">8 GB LPDDR4X RAM</li>,
 <li class="DTBslk">64 bit Android Operating System</li>,
 <li class="DTBslk">39.62 cm (15.6 Inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core i7 Processor (13th Gen)</li>,
 <li class="DTBslk">32 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">Included Software- Microsoft Office Home 2024(includes Word, Excel, PowerPoint, and OneNote) (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), McAfee+TM Premium (1 year Validity)</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>,
 <li class="DTBslk">Intel Core 3 Processor (14th Gen)</li>,
 <li class="DTBslk">8 GB DDR5 RAM</li>,
 <li class="DTBslk">64 bit Windows 11 Home Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Limited Warranty</li>,
 <li class="DTBslk">Intel Core i3 Processor (13th Gen)</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">512 GB SSD</li>,
 <li class="DTBslk">35.56 cm (14 Inch) Display</li>,
 <li class="DTBslk">1 Year Carry-in Warranty</li>,
 <li class="DTBslk">AMD Ryzen 3 Quad Core Processor</li>,
 <li class="DTBslk">8 GB DDR4 RAM</li>,
 <li class="DTBslk">Windows 11 Operating System</li>,
 <li class="DTBslk">256 GB SSD</li>,
 <li class="DTBslk">39.62 cm (15.6 inch) Display</li>,
 <li class="DTBslk">1 Year Onsite Warranty</li>]

In [33]:
a=soup.find_all("li",class_="DTBslk")[4].text
a

'39.62 cm (15.6 Inch) Display'

In [34]:
re.findall(r"(\d+)\s.+",a)

['62']

In [35]:
display=[]
for tag in soup.find_all("li",class_="DTBslk"):
    text=tag.text
    a=re.findall(r"(\d+)\s.+",text)
    display.extend(a)
display

['5',
 '8',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '64',
 '256',
 '62',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '3',
 '8',
 '11',
 '512',
 '62',
 '2024',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '4',
 '32',
 '128',
 '56',
 '1',
 '2',
 '32',
 '64',
 '512',
 '05',
 '1',
 '3',
 '8',
 '64',
 '256',
 '56',
 '1',
 '12',
 '11',
 '512',
 '62',
 '1',
 '7',
 '16',
 '64',
 '512',
 '62',
 '1',
 '5',
 '16',
 '64',
 '512',
 '62',
 '1',
 '16',
 '11',
 '512',
 '56',
 '2024',
 '1',
 '2',
 '16',
 '64',
 '512',
 '1',
 '1',
 '5',
 '8',
 '64',
 '512',
 '62',
 '1',
 '7',
 '16',
 '64',
 '512',
 '62',
 '1',
 '7',
 '32',
 '64',
 '1',
 '62',
 '1',
 '7',
 '16',
 '64',
 '1',
 '62',
 '1',
 '9',
 '32',
 '11',
 '2',
 '64',
 '2024',
 '1',
 '99',
 '8',
 '64',
 '62',
 '1',
 '7',
 '32',
 '64',
 '512',
 '56',
 '365',
 '1',
 '3',
 '8',
 '64',
 '512',
 '56',
 '1',
 '3',
 '8',
 '11',
 '512',
 '56',
 '1',
 '3',
 '8',
 '11',
 '256',
 '62',
 '1']

### Extracting price

In [36]:
a=soup.find_all("div",class_="hZ3P6w DeU9vF")[0].text
a

'₹55,311'

In [37]:
re.findall(r"₹(.+)", a)

['55,311']

In [38]:
price=[]

for tag in soup.find_all("div",class_="hZ3P6w DeU9vF"):
    text=tag.text
    a=re.findall(r"₹(.+)", text)
    price.extend(a)
price

['55,311',
 '51,990',
 '39,990',
 '59,990',
 '42,990',
 '82,951',
 '15,390',
 '2,67,990',
 '37,990',
 '39,938',
 '89,440',
 '75,371',
 '58,990',
 '2,09,990',
 '55,311',
 '77,990',
 '97,050',
 '1,25,170',
 '4,99,990',
 '29,990',
 '89,990',
 '50,990',
 '42,990',
 '48,104']

### Extracting Original price

In [39]:
a=soup.find_all("div",class_="kRYCnD gxR4EY")[0].text
a

'₹78,189'

In [40]:
re.findall(r"₹(.+)", a)

['78,189']

In [41]:
original_price=[]

for tag in soup.find_all("div",class_="kRYCnD gxR4EY"):
    text=tag.text
    a=re.findall(r"₹(.+)", text)
    original_price.extend(a)
original_price

['78,189',
 '57,499',
 '74,999',
 '78,999',
 '50,990',
 '99,990',
 '30,000',
 '2,69,999',
 '48,999',
 '46,990',
 '1,09,990',
 '79,900',
 '1,14,990',
 '2,11,999',
 '78,189',
 '94,999',
 '1,46,990',
 '1,27,990',
 '5,93,990',
 '34,990',
 '1,29,990',
 '69,990',
 '58,990',
 '51,999']

### Extracting Discount

In [42]:
a=soup.find_all("span")
a

[<span class="stfyUS">Plus</span>,
 <span>Become a Seller</span>,
 <span>Cart</span>,
 <span>Filters</span>,
 <span>CATEGORIES</span>,
 <span><svg class="QASjE5" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg"><path class="zMV6HH" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></span>,
 <span><svg class="QASjE5" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg"><path class="" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></span>,
 <span>63 MORE</span>,
 <span>Price</span>,
 <span class="question">?</span>,
 <span>Need help?</span>,
 <span>Help me decide</span>,
 <span class="_Omnvo">Showing 1 – 24 of 2,258 results for "<span>laptops</span>"</span>,
 <span>laptops</span>,
 <span class="bTZV6I">Sort By</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMGZUYDFZXHWYWZJ6V2KW_COMGZUYDFZXHWYWZ_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>19,735 Ratings </span><span class="o2SIOJ">&amp;</span><span> 2,048 Reviews</span></span></span>,
 <span><span>19,735 Ratings </span><span class="o2SIOJ">&amp;</span><span> 2,048 Reviews</span></span>,
 <span>19,735 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 2,048 Reviews</span>,
 <span>29% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMH4Y6KKRC9YSWERDUMZD_COMH4Y6KKRC9YSWE_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>10,664 Ratings </span><span class="o2SIOJ">&amp;</span><span> 1,222 Reviews</span></span></span>,
 <span><span>10,664 Ratings </span><span class="o2SIOJ">&amp;</span><span> 1,222 Reviews</span></span>,
 <span>10,664 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 1,222 Reviews</span>,
 <span>9% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHMHYH9GDHGXDAYAE4GK_COMHMHYH9GDHGXDA_"><div class="MKiFS6">3.7<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>36 Ratings </span><span class="o2SIOJ">&amp;</span><span> 6 Reviews</span></span></span>,
 <span><span>36 Ratings </span><span class="o2SIOJ">&amp;</span><span> 6 Reviews</span></span>,
 <span>36 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 6 Reviews</span>,
 <span>46% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHMYD8FQU2Z8QGCCSRS3_COMHMYD8FQU2Z8QG_"><div class="MKiFS6">4.5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>33 Ratings </span><span class="o2SIOJ">&amp;</span><span> 3 Reviews</span></span></span>,
 <span><span>33 Ratings </span><span class="o2SIOJ">&amp;</span><span> 3 Reviews</span></span>,
 <span>33 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 3 Reviews</span>,
 <span>24% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHGWQY66YNGVFKYKVYYT_COMHGWQY66YNGVFK_"><div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>1,341 Ratings </span><span class="o2SIOJ">&amp;</span><span> 105 Reviews</span></span></span>,
 <span><span>1,341 Ratings </span><span class="o2SIOJ">&amp;</span><span> 105 Reviews</span></span>,
 <span>1,341 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 105 Reviews</span>,
 <span>15% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHE4ATPCZ9FXRP7N1GVG_COMHE4ATPCZ9FXRP_"><div class="MKiFS6">4.6<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>841 Ratings </span><span class="o2SIOJ">&amp;</span><span> 125 Reviews</span></span></span>,
 <span><span>841 Ratings </span><span class="o2SIOJ">&amp;</span><span> 125 Reviews</span></span>,
 <span>841 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 125 Reviews</span>,
 <span>17% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span>48% off</span>,
 <span class="nvcpki">Pre Order</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMGFHMJFHEDTDD4K35NBB_COMGFHMJFHEDTDD4_"><div class="MKiFS6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>588 Ratings </span><span class="o2SIOJ">&amp;</span><span> 64 Reviews</span></span></span>,
 <span><span>588 Ratings </span><span class="o2SIOJ">&amp;</span><span> 64 Reviews</span></span>,
 <span>588 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 64 Reviews</span>,
 <span>22% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMH59ENQYHDYJGX1QWEL9_COMH59ENQYHDYJGX_"><div class="MKiFS6">3.9<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>3,887 Ratings </span><span class="o2SIOJ">&amp;</span><span> 310 Reviews</span></span></span>,
 <span><span>3,887 Ratings </span><span class="o2SIOJ">&amp;</span><span> 310 Reviews</span></span>,
 <span>3,887 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 310 Reviews</span>,
 <span>15% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHE4ATBCUTGUYTJZ7NHN_COMHE4ATBCUTGUYT_"><div class="MKiFS6">4.6<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>464 Ratings </span><span class="o2SIOJ">&amp;</span><span> 65 Reviews</span></span></span>,
 <span><span>464 Ratings </span><span class="o2SIOJ">&amp;</span><span> 65 Reviews</span></span>,
 <span>464 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 65 Reviews</span>,
 <span>18% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMGVQ2YB9SU8KMFHA5MEW_COMGVQ2YB9SU8KMF_"><div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>847 Ratings </span><span class="o2SIOJ">&amp;</span><span> 52 Reviews</span></span></span>,
 <span><span>847 Ratings </span><span class="o2SIOJ">&amp;</span><span> 52 Reviews</span></span>,
 <span>847 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 52 Reviews</span>,
 <span>5% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHCQ5ED4R4MAEXMLWR80_COMHCQ5ED4R4MAEX_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>702 Ratings </span><span class="o2SIOJ">&amp;</span><span> 69 Reviews</span></span></span>,
 <span><span>702 Ratings </span><span class="o2SIOJ">&amp;</span><span> 69 Reviews</span></span>,
 <span>702 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 69 Reviews</span>,
 <span>48% off</span>,
 <span class="nvcpki">Pre Order</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMGZUYDFZXHWYWZJ6V2KW_COMGZUYDFZXHWYWZ_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>19,735 Ratings </span><span class="o2SIOJ">&amp;</span><span> 2,048 Reviews</span></span></span>,
 <span><span>19,735 Ratings </span><span class="o2SIOJ">&amp;</span><span> 2,048 Reviews</span></span>,
 <span>19,735 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 2,048 Reviews</span>,
 <span>29% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHGEUYCPDCFWNNCDEDDP_COMHGEUYCPDCFWNN_"><div class="MKiFS6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>48 Ratings </span><span class="o2SIOJ">&amp;</span><span> 5 Reviews</span></span></span>,
 <span><span>48 Ratings </span><span class="o2SIOJ">&amp;</span><span> 5 Reviews</span></span>,
 <span>48 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 5 Reviews</span>,
 <span>17% off</span>,
 <span class="fRrrYo">Currently unavailable</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHE4ATYBXNJG4F0L9HXI_COMHE4ATYBXNJG4F_"><div class="MKiFS6">4.1<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>36 Ratings </span><span class="o2SIOJ">&amp;</span><span> 11 Reviews</span></span></span>,
 <span><span>36 Ratings </span><span class="o2SIOJ">&amp;</span><span> 11 Reviews</span></span>,
 <span>36 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 11 Reviews</span>,
 <span>33% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHE4ATY22ZRYNGQNKUJ6_COMHE4ATY22ZRYNG_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>61 Ratings </span><span class="o2SIOJ">&amp;</span><span> 12 Reviews</span></span></span>,
 <span><span>61 Ratings </span><span class="o2SIOJ">&amp;</span><span> 12 Reviews</span></span>,
 <span>61 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 12 Reviews</span>,
 <span>2% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span>15% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHDGD5CQJVZUH73W3DYP_COMHDGD5CQJVZUH7_"><div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>1,562 Ratings </span><span class="o2SIOJ">&amp;</span><span> 532 Reviews</span></span></span>,
 <span><span>1,562 Ratings </span><span class="o2SIOJ">&amp;</span><span> 532 Reviews</span></span>,
 <span>1,562 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 532 Reviews</span>,
 <span>14% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMH8Z2QT98FWRGHHOIA2G_COMH8Z2QT98FWRGH_"><div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>997 Ratings </span><span class="o2SIOJ">&amp;</span><span> 93 Reviews</span></span></span>,
 <span><span>997 Ratings </span><span class="o2SIOJ">&amp;</span><span> 93 Reviews</span></span>,
 <span>997 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 93 Reviews</span>,
 <span>30% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMHGYAFPJ2BGX6HVGQ2CF_COMHGYAFPJ2BGX6H_"><div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>6,599 Ratings </span><span class="o2SIOJ">&amp;</span><span> 623 Reviews</span></span></span>,
 <span><span>6,599 Ratings </span><span class="o2SIOJ">&amp;</span><span> 623 Reviews</span></span>,
 <span>6,599 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 623 Reviews</span>,
 <span>27% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,
 <span class="CjyrHS" id="productRating_LSTCOMGMV6V6ZAUMWEHX12DJK_COMGMV6V6ZAUMWEH_"><div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span>,
 <span class="PvbNMB"><span><span>224 Ratings </span><span class="o2SIOJ">&amp;</span><span> 32 Reviews</span></span></span>,
 <span><span>224 Ratings </span><span class="o2SIOJ">&amp;</span><span> 32 Reviews</span></span>,
 <span>224 Ratings </span>,
 <span class="o2SIOJ">&amp;</span>,
 <span> 32 Reviews</span>,
 <span>27% off</span>,
 <span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span>,
 <span>Add to Compare</span>,

In [43]:
t="44% off"
re.findall(r"(\d+)\%\s",t)

['44']

In [44]:
discount=[]
for tag in soup.find_all('span'):
    text=tag.text
    a=re.findall(r"(\d+)\%\s",text)
    discount.extend(a)

discount

['29',
 '9',
 '46',
 '24',
 '15',
 '17',
 '48',
 '22',
 '15',
 '18',
 '5',
 '48',
 '29',
 '17',
 '33',
 '2',
 '15',
 '14',
 '30',
 '27',
 '27',
 '7',
 '29',
 '17',
 '15',
 '2',
 '33']

### Extracting Ratings

In [45]:
a=soup.find_all("div",class_="MKiFS6")
a

[<div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">3.7<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.6<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">3.9<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.6<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.1<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.1<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">3.9<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 pnieuf ojKpP6">1<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">5<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6">4.1<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>,
 <div class="MKiFS6 ojKpP6">3<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>]

In [46]:
a=soup.find_all("div",class_="MKiFS6")[0].text
a

'4.4'

In [47]:
ratings=[]

for tag in soup.find_all("div",class_="MKiFS6"):
    text=tag.text
    a=re.findall(r"(.+)",text)
    ratings.extend(a)
ratings

['4.4',
 '4.4',
 '3.7',
 '4.5',
 '4.3',
 '4.6',
 '4',
 '3.9',
 '4.6',
 '4.3',
 '4.4',
 '4.4',
 '4',
 '4.1',
 '4.4',
 '4.4',
 '4.3',
 '4.3',
 '4.3',
 '4.1',
 '4.4',
 '5',
 '4',
 '4',
 '5',
 '4',
 '3.9',
 '4',
 '1',
 '4.4',
 '5',
 '5',
 '4.1',
 '3',
 '3']

In [48]:
import requests
import re
from bs4 import BeautifulSoup


brand=[]
Brand_title=[]
processor=[]
ram=[]
ssd=[]
display=[]
price=[]
original_price=[]
discount=[]
ratings=[]
headers={"User-Agent":"Mozilla/5.0"}
for page in range(1,11):
    url=f"https://www.flipkart.com/search?q=laptops&as=on&as-show=on&otracker=AS_Query_TrendingAutoSuggest_1_0_na_na_na&otracker1=AS_Query_TrendingAutoSuggest_1_0_na_na_na&as-pos=1&as-type=HISTORY&suggestionId=laptops&requestId=8809d76a-c51d-49f1-b6a9-23641fb8f697&page={page}"

    response = requests.get(url,headers=headers)
    soup = BeautifulSoup(response.content,"html.parser")
    for tag in soup.find_all("div",class_="RG5Slk"):
        text=tag.text
        a=re.findall(r"(.+)\s\-",text)
        brand.extend(a)
        
    for tag in soup.find_all("div",class_="RG5Slk"):
        text=tag.text
        a= re.findall(r"^[A-Za-z]+", text)
        Brand_title.extend(a)
    for tag in soup.find_all("li",class_="DTBslk"):
        text=tag.text
        a=re.findall(r"(.+)",text)
        processor.extend(a)
        
    for tag in soup.find_all("li",class_="DTBslk"):
        text=tag.text
        a=re.findall(r"(\d+).+RAM",text)
        ram.extend(a)
    
    for tag in soup.find_all("li",class_="DTBslk"):
        text=tag.text
        a=re.findall(r"(\d+)\s.+",text)
        ssd.extend(a)
    for tag in soup.find_all("li",class_="DTBslk"):
        text=tag.text
        a=re.findall(r"(\d+)\s.+",text)
        display.extend(a)
    for tag in soup.find_all("div",class_="hZ3P6w DeU9vF"):
        text=tag.text
        a=re.findall(r"₹(.+)",text)
        price.extend(a)
    for tag in soup.find_all("div",class_="kRYCnD gxR4EY"):
        text=tag.text
        a=re.findall(r"₹(.+)", text)
        original_price.extend(a)
    for tag in soup.find_all('span'):
        text=tag.text
        a=re.findall(r"(\d+)\%\s",text)
        discount.extend(a)
    for tag in soup.find_all("div",class_="MKiFS6"):
        text=tag.text
        a=re.findall(r"(.+)",text)
        ratings.extend(a)
    print(f"page {page} is scraped")

page 1 is scraped
page 2 is scraped
page 3 is scraped
page 4 is scraped
page 5 is scraped
page 6 is scraped
page 7 is scraped
page 8 is scraped
page 9 is scraped
page 10 is scraped

In [49]:
print(brand, Brand_title,processor,ram,ssd,display,price,original_price,discount,ratings)

['Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'Acer Aspire 15 MS Office 2024 + M365 Basic, AMD Ryzen 3 Quad Core 7330U', 'Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 210H', 'ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic* Intel Core i3 13th Gen', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'walker Intel Celeron Dual Core Intel N4020', 'MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus', 'Acer One 14 AMD Ryzen 3 Quad Core 7320U', 'Acer Aspire 3 Intel Pentium Quad Core N6000', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X', 'MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'ASUS ROG Zephyrus G16 OLED (2026) Intel Core Ultra 9 386H', 'Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781)', 'ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H', 'ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U', 'MSI Modern 14 Intel Core i3 13th Gen 1315U', 'Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U', 'Primebook 2 Pro (2025) in-Built AI MediaTek Helio G99 (MT8781)', 'ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'Acer Aspire Lite AMD Ryzen 3 Quad Core 5300U', 'ASUS Vivobook 16 (2025) with Office 2024 + M365 Basic* Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP 14 AI PC Intel Core Ultra 7 155H', 'ASUS Expertbook P3 Metal High-performance processor with 1 Yr ADP Intel Core i7 13th Gen 13620H', 'ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150', 'ASUS Vivobook Go 14 (2026) with Office 2024 + M365 Basic AMD Ryzen 3 Quad Core 30', 'Acer Aspire 3 Intel Celeron Dual Core', 'Infinix Y3Plus Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic*, Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X', 'Lenovo Yoga Slim 7 WUXGA OLED with 1Yr ADP Intel Core Ultra 9 185H', 'ASUS Vivobook 15 Intel Core i3 12th Gen 1215U', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'HP Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic*, Intel Core i3 13th Gen 1315U', 'Lenovo Chromebook 11IJL9 Intel Celeron Dual Core N4500', 'HP G9 Intel Core i3 13th Gen 1315U', 'Infinix ZEROBOOK 13 Intel Intel Core i9 13th Gen 13900H', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'Lenovo IdeaPad Slim 1 AMD Ryzen 5 Hexa Core 5500U', 'HP Essentials(i5 14th Gen) Intel Core 5 13th Gen 120U', 'HP 15 (2025) AMD Ryzen 3 Quad Core 7320U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Intel Core Ultra 5 225H', 'ASUS Expertbook P1 with 1 Yr ADP(i3 14th Gen) Intel Core 3 13th Gen 1315U', 'Acer Aspire Intel Core i5 12th Gen 12450H', 'ASUS ROG Strix G16 (2026) AMD Ryzen 9 16 Core 8940HX', 'Lenovo Ideapad Slim 3 OLED with 1Yr ADP Snapdragon X', 'HP 15 G10 (2025) AMD Athlon Dual Core 7120U', 'ASUS Chromebook CX14 Intel Celeron Dual Core N50', 'ASUS Expertbook P3 Metal High-performance processor with 1 Yr ADP Intel Core i5 13th Gen 13420H', 'Acer Predator Helios Neo 16S AI Intel Core Ultra 7 255HX', 'ASUS Vivobook 15 (2025) with Touchscreen & Backlit Keyboard, Intel Core i3 13th Gen 1315U', 'HP 14 AI PC Intel Core Ultra 7 155H', 'HP Professional 14, Intel Core i5 13th Gen 1334U', 'Acer Swift Neo Office 2024 + M365 Basic Intel Core Ultra 7 155U', 'HP Victus(i5 14th Gen) Intel Core 5 210H', 'ASUS Vivobook 16 (2025) with Office 2024 + M365 Basic, AI PC Intel Core Ultra 5 Series 2 225H', 'ASUS Vivobook Go 15 (2026) with Office 2024 + M365 Basic* AMD Ryzen 3 Quad Core 30', 'HP Victus AMD Ryzen 7 Hexa Core 7445HS', 'Acer Aspire AMD Ryzen 5 Hexa Core 7430U', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'Acer Aspire 15 AMD Ryzen 3 Quad Core 7330U', 'Acer Aspire Lite AMD Ryzen 3 Quad Core 5300U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'MOTOROLA Motobook 60 Pro Full Metal AI PC WUXGA OLED Intel Core Ultra 5 225H', 'Lenovo IdeaPad Slim 1 AMD Ryzen 5 Hexa Core 5500U', 'HP 15 (2024) AMD Ryzen 3 Quad Core 7320U', 'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Samsung Galaxy Book4 Metal Intel Core i7 13th Gen 1355U', 'ASUS V16 (2025) for Creator with Office 2024 + M365 Basic*,AI PC (i5 14th Gen) Intel Core 5 210H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP OmniBook 5(Previously Pavilion) Intel Core i5 13th Gen 1334U', 'DELL Inspiron Intel Core i3 6th Gen 6100U', 'ASUS Vivobook S14 (2025) with Office 2024 + M365 Basic*, AI PC, Backlit Keyboard, Snapdragon X', 'ASUS Vivobook 15, with Backlit Keyboard, Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 15 Intel Core i5 12th Gen 1235U', 'Acer Aspire 3 Intel Celeron Dual Core', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U', 'HP 15s Metal Intel Core i3 13th Gen 1315U', 'Acer Swift Lite 14 Intel Core Ultra 5 115U', 'Acer Aspire 3 Intel Core i3 12th Gen 1215U', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Lenovo IdeaPad Slim 3 WUXGA IPS Intel Core i5 13th Gen 13420H', 'ASUS TUF Gaming F16 (2025) with MSO 2024+M365 Basic (i5 14th Gen) Intel Core 5', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', "Lenovo IdeaPad Slim 3 Backlit Keyboard with MSO'2024 Intel Core i5 13th Gen 13420H", 'DELL 15 (Previously Inspiron) (2025) Microsoft Office Home 2024 AMD Ryzen 5 Hexa Core 7530U', 'ASUS Expertbook P1 with 1 Yr ADP (i5 14th Gen) Intel Core 5 210H', 'Acer Nitro V 15 Intel Core i5 13th Gen 13420H', 'ASUS Vivobook 16 (2025) with MSO 2024 + M365 Basic* AMD Ryzen 5 Hexa Core', 'ASUS ExpertBook P3 Intel Core Ultra 7 255H', 'ASUS Vivobook 15 (2025)(i5 14th Gen)with MSO 2024 + M365 Basic, Backlit Keyboard, Intel Core 5 120U', 'Acer Aspire Lite Intel Core i5 12th Gen 12450H', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'ASUS Expertbook P3 Metal High-performance processor with 1 Yr ADP Intel Core i5 13th Gen 13420H', 'Acer Aspire Lite Intel Core i3 13th Gen 1305U', 'ASUS Vivobook Go 15 (2026) with Office 2024 + M365 Basic* AMD Ryzen 3 Quad Core 30', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Intel Core Ultra 5 225H', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP Omnibook 3 with Backlit Keyboard AMD Ryzen AI 5 Quad Core', 'Acer Aspire 3 Intel Celeron Dual Core', 'MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite', 'Acer Predator Helios Neo 16S AI Intel Core Ultra 7 255HX', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'walker Intel Celeron Dual Core Intel N4020', 'Infinix Y3Plus Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 16 (2025), Copilot + PC with Backlit Keyboard, AI PC, Snapdragon X', 'ASUS Vivobook (i5 14th Gen) Intel Core 5 120U', "Lenovo IdeaPad Slim 3 Backlit Keyboard with MSO'2024 Intel Core i5 13th Gen 13420H", 'DELL 14 Plus Next Gen AI PC Microsoft Office Home 2024 Intel Core Ultra 5 226V', 'ASUS Vivobook 14(i5 14th Gen) Intel Core 5 120U', 'Lenovo Ideapad Slim 3 OLED with 1Yr ADP Snapdragon X', 'HP 15 (i3 14th Gen) Intel Core 3 100U', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'ASUS Vivobook 16 (2025) with MSO 2024 + M365 Basic* AMD Ryzen 5 Hexa Core', 'HP Pavilion Intel Core i5 13th Gen 1340P', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'ASUS ROG Zephyrus G14 (2025) with Office 2024 + M365 Basic* AMD Ryzen 9 Octa Core', 'ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150', 'ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H', 'Acer Aspire Intel Core i5 12th Gen 12450H', 'ASUS TUF Gaming A16 (2026) with Office 2024 + M365 Basic AMD Ryzen 7 260', 'Lenovo IdeaPad Slim 3 WUXGA IPS Intel Core i5 13th Gen 13420H', 'Infinix Intel Core i7 10th Gen 1065G7', 'Acer Aspire Intel Core i5 12th Gen 12450H', 'HP 14 AI PC Intel Core Ultra 7 155H', 'DELL 15 (Previously Inspiron) AI Powered Intel Core Ultra 5 225H', 'HP Victus AMD Ryzen 7 Hexa Core 7445HS', 'HP OMEN (i7 14th Gen) Intel Core 7 240H', 'HP 255 G10 AMD Athlon Dual Core 7120U', 'Lenovo LOQ Intel Core i5 13th Gen 13450HX', 'Acer Aspire with Infinity Learn Neet Pro Course Intel Celeron Dual Core N4500', 'ASUS ROG Strix SCAR 16 (2025) with Office 2024 + M365 Basic* Intel Core Ultra 9 275HX', 'HP 250R G10 (2025) (i3 14th Gen) Intel Core 3 14th Gen 100U', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'ASUS ExpertBook P3 Intel Core Ultra 7 255H', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic* (i5 14th Gen) Intel Core 5 120U', 'HP 15 (i3 14th Gen) Intel Core 3 100U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'ASUS Vivobook 14 Flip OLED (2026) with Touch Screen, Metallic Design, Intel Core Ultra 5 226V', 'Lenovo LOQ 2025 AMD Ryzen 5 Quad Core 7235HS', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP Intel Core i5 13th Gen 13420H', 'ASUS Vivobook S14 (2025) with Office 2024 + M365 Basic*, AI PC, Backlit Keyboard, Snapdragon X', 'ASUS Expertbook P1 with 1 Yr ADP (i5 14th Gen) Intel Core 5 210H', 'ASUS Vivobook 15, with Backlit Keyboard, Intel Core i3 13th Gen 1315U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Lenovo 100e Chromebook Gen 4 MediaTek Kompanio 520', 'ASUS Vivobook Go 15 OLED AMD Ryzen 3 Quad Core 7320U', 'Infinix X1 Slim Series Intel Core i5 10th Gen 1035G1', 'ASUS ROG Zephyrus G14 (2025) with Office 2024 + M365 Basic* AMD Ryzen AI 9 12 Core HX 370', 'DELL Intel Core i3 13th Gen', 'ASUS TUF Gaming A16 (2026) with Office 2024 + M365 Basic AMD Ryzen 7 260', 'ASUS Expertbook P1 with 1 Yr ADP(i3 14th Gen) Intel Core 3 13th Gen 1315U', 'Samsung Galaxy Book6 Intel Core Ultra 7 Series 3 355', 'Lenovo IdeaPad Slim 3 WUXGA IPS with 1Yr ADP Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'HP 15 Intel Celeron Dual Core 12th Gen', 'HP 15 (i5 14th Gen) Intel Core 5 120U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Acer Aspire 3 Intel Core i3 12th Gen 1215U', 'ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Intel Core Ultra 5 225H', 'MSI Prestige 13 Evo AI PC Intel Core Ultra 5 125H', 'HP 15 (2025) Intel Core i3 13th Gen 1315U', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Lenovo IdeaPad Slim 5 with 1Yr ADP Intel Core Ultra 5 125 H', 'ZEBRONICS Thin and Light Laptop Intel Core i7 12th Gen 1255U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'Acer Aspire Lite AMD Ryzen 5 Hexa Core 5625U', 'HP 255 G10 AMD Athlon Dual Core 7120U', 'HP Victus Intel Core i5 12th Gen 12450H', 'HP 250R G10 (2025) (i3 14th Gen) Intel Core 3 14th Gen 100U', 'MSI Katana 15 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U', 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U', 'DELL 15 (Previously Inspiron) AI Powered Intel Core Ultra 5 225H', 'Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'DELL 15 (Previouly Inspiron) AMD Ryzen 5 Quad Core 7520U', 'ASUS Chromebook Intel Celeron Dual Core N4500', 'HP 15 (2025) AMD Athlon Dual Core 7120U', 'Lenovo THINKBOOK 16 AMD Ryzen 5 Hexa Core 7th Gen 7535HS', 'Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP 250R G10 (2025) (i3 14th Gen) Intel Core 3 14th Gen 100U', 'Acer Aspire Lite AMD Ryzen 3 Quad Core 5300U', 'Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U', 'HP 14 AI PC Intel Core Ultra 7 155H', 'HP Victus AMD Ryzen 7 Hexa Core 7445HS', 'Acer Aspire with Infinity Learn Neet Pro Course Intel Celeron Dual Core N4500', 'ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150', 'ASUS Vivobook 15 (2025)(i5 14th Gen)with MSO 2024 + M365 Basic, Backlit Keyboard, Intel Core 5 120U', 'MSI Modern 14 C13M Intel Core i3 13th Gen 1315U', 'ASUS Vivobook S14 (2025) with Backlit Keyboard, Metallic Design*, Intel Core Ultra 7 255H', 'HP 15q Intel Core i5 8th Gen 8265U', 'ZEBRONICS Pro Series Z Intel Core i7 12th Gen 1255U'] ['Samsung', 'Samsung', 'Acer', 'Acer', 'ASUS', 'Samsung', 'walker', 'MICROSOFT', 'Acer', 'Acer', 'Samsung', 'Lenovo', 'ASUS', 'MICROSOFT', 'Samsung', 'Acer', 'Samsung', 'Samsung', 'ASUS', 'Primebook', 'ASUS', 'ASUS', 'MSI', 'Acer', 'Primebook', 'ASUS', 'Samsung', 'Samsung', 'Acer', 'ASUS', 'Samsung', 'Samsung', 'HP', 'ASUS', 'ASUS', 'ASUS', 'ASUS', 'Acer', 'Infinix', 'ASUS', 'ASUS', 'ASUS', 'Lenovo', 'ASUS', 'Samsung', 'HP', 'ASUS', 'Lenovo', 'HP', 'Infinix', 'Samsung', 'Samsung', 'Lenovo', 'HP', 'Lenovo', 'HP', 'Samsung', 'Samsung', 'ASUS', 'ASUS', 'Acer', 'ASUS', 'Lenovo', 'HP', 'ASUS', 'ASUS', 'Acer', 'ASUS', 'HP', 'HP', 'Acer', 'HP', 'ASUS', 'ASUS', 'HP', 'Acer', 'Samsung', 'Samsung', 'Acer', 'Acer', 'Samsung', 'Samsung', 'MOTOROLA', 'Lenovo', 'HP', 'Lenovo', 'Lenovo', 'Samsung', 'Samsung', 'ASUS', 'Samsung', 'HP', 'DELL', 'ASUS', 'ASUS', 'ASUS', 'Samsung', 'Samsung', 'ASUS', 'Acer', 'Samsung', 'Samsung', 'Acer', 'HP', 'Acer', 'Acer', 'Lenovo', 'Samsung', 'Lenovo', 'ASUS', 'Samsung', 'ASUS', 'Lenovo', 'DELL', 'ASUS', 'Acer', 'ASUS', 'ASUS', 'ASUS', 'Acer', 'Samsung', 'Samsung', 'ASUS', 'Acer', 'ASUS', 'Samsung', 'Samsung', 'Samsung', 'MICROSOFT', 'ASUS', 'Lenovo', 'Samsung', 'HP', 'Acer', 'MICROSOFT', 'Acer', 'Samsung', 'walker', 'Infinix', 'ASUS', 'ASUS', 'Lenovo', 'DELL', 'ASUS', 'Lenovo', 'HP', 'Samsung', 'Samsung', 'ASUS', 'HP', 'Samsung', 'Samsung', 'ASUS', 'ASUS', 'ASUS', 'Acer', 'ASUS', 'Lenovo', 'Infinix', 'Acer', 'HP', 'ASUS', 'DELL', 'HP', 'HP', 'HP', 'Lenovo', 'Acer', 'ASUS', 'HP', 'Samsung', 'Samsung', 'ASUS', 'ASUS', 'HP', 'ASUS', 'Samsung', 'Samsung', 'ASUS', 'Lenovo', 'Lenovo', 'Samsung', 'HP', 'ASUS', 'ASUS', 'ASUS', 'Samsung', 'Lenovo', 'ASUS', 'Infinix', 'ASUS', 'DELL', 'ASUS', 'ASUS', 'Samsung', 'Lenovo', 'Samsung', 'Samsung', 'HP', 'HP', 'Samsung', 'Samsung', 'Acer', 'ASUS', 'MSI', 'HP', 'Lenovo', 'Samsung', 'Lenovo', 'ZEBRONICS', 'Samsung', 'Acer', 'HP', 'HP', 'HP', 'MSI', 'Samsung', 'Samsung', 'DELL', 'Acer', 'Samsung', 'Samsung', 'DELL', 'ASUS', 'HP', 'Lenovo', 'Lenovo', 'Samsung', 'HP', 'Acer', 'Samsung', 'HP', 'HP', 'Acer', 'ASUS', 'ASUS', 'MSI', 'ASUS', 'HP', 'ZEBRONICS'] ['Intel Core i5 Processor (13th Gen)', '8 GB LPDDR4X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories', 'Intel Core i3 Processor (13th Gen)', '8 GB LPDDR4X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Year Onsite Warranty', 'AMD Ryzen 3 Quad Core Processor', '8 GB DDR4 RAM', '64 bit Windows 11 Home Operating System', '256 GB SSD', '39.62 cm (15.6 inch) Display', 'MSO', '1 Year Onsite Service', 'Intel Core 5 Processor', '16 GB LPDDR5 RAM', '64 bit Windows 11 Home Operating System', '512 GB SSD', '39.62 cm (15.6 inch) Display', '1 Year Onsite Service', 'Intel Core i3 Processor (13th Gen)', '8 GB DDR5 RAM', 'Windows 11 Home Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', 'Microsoft Office Home 2024 + Microsoft 365 Basic', '1 Year Onsite Warranty', 'Intel Core Ultra 7 Processor', '16 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', 'MS Office Home and Student 2024', '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories', 'Intel Celeron Dual Core Processor', '4 GB DDR4 RAM', '32 bit Windows 11 Operating System', '128 GB SSD', '35.56 cm (14 inch) Display', '1 Year Onsite Service', 'Snapdragon X2 Plus Processor', '32 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '35.05 cm (13.8 inch) Touchscreen Display', 'NA', '1 Year Onsite Service', 'AMD Ryzen 3 Quad Core Processor', '8 GB LPDDR5 RAM', '64 bit Windows 11 Operating System', '256 GB SSD', '35.56 cm (14 Inch) Display', '1 Year International Travelers Warranty (ITW)', 'Intel Pentium Quad Core Processor', '12 GB LPDDR4X RAM', 'Windows 11 Home Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Year International Travelers Warranty (ITW)', 'Intel Core Ultra 5 Processor', '16 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', 'MS Office Home and Student 2024', '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories', 'Intel Core i5 Processor (13th Gen)', '16 GB LPDDR5 RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Yr. Onsite + 1 Yr. Accidental Damage Protection', 'Snapdragon X Processor', '16 GB LPDDR5X RAM', 'Windows 11 Home Operating System', '512 GB SSD', '35.56 cm (14 Inch) Display', 'Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps', '1 Year Onsite Warranty', 'Snapdragon X2 Elite Processor', '16 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '38.1 cm (15 inch) Touchscreen Display', 'NA', '1 Year Onsite Service', 'Intel Core i5 Processor (13th Gen)', '8 GB LPDDR4X RAM', '64 bit Windows 11 Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories', 'Intel Core 7 Processor', '16 GB DDR4 RAM', '64 bit Windows 11 Home Operating System', '512 GB SSD', '39.62 cm (15.6 Inch) Display', '1 Year Warranty', 'Intel Core Ultra 7 Processor', '32 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '1 TB SSD', '39.62 cm (15.6 Inch) Display', 'MS Office Home and Student 2024', '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories', 'Intel Core Ultra 7 Processor', '16 GB LPDDR5X RAM', '64 bit Windows 11 Operating System', '1 TB SSD', '39.62 cm (15.6 Inch) Display', 'MS Office Home and Student 2024', '1 Year Manufacturer Warra

In [50]:
print(len(brand),len(Brand_title),len(processor),len(ram),len(ssd),len(display),len(price),len(original_price),len(discount),len(ratings))

234 240 1573 240 1482 1482 240 221 261 376

In [51]:
from itertools import zip_longest

data=list(zip_longest(brand,Brand_title,processor,ram,ssd,display,price,original_price,discount,ratings))
data

[('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'Samsung',
  'Intel Core i5 Processor (13th Gen)',
  '8',
  '5',
  '5',
  '55,311',
  '78,189',
  '29',
  '4.4'),
 ('Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
  'Samsung',
  '8 GB LPDDR4X RAM',
  '8',
  '8',
  '8',
  '51,990',
  '57,499',
  '9',
  '4.4'),
 ('Acer Aspire 15 MS Office 2024 + M365 Basic, AMD Ryzen 3 Quad Core 7330U',
  'Acer',
  '64 bit Windows 11 Operating System',
  '8',
  '64',
  '64',
  '39,990',
  '74,999',
  '46',
  '3.7'),
 ('Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 210H',
  'Acer',
  '512 GB SSD',
  '16',
  '512',
  '512',
  '59,990',
  '78,999',
  '24',
  '4.5'),
 ('ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic* Intel Core i3 13th Gen',
  'ASUS',
  '39.62 cm (15.6 Inch) Display',
  '8',
  '62',
  '62',
  '42,990',
  '50,990',
  '15',
  '4.3'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
  '16',
  '1',
  '1',
  '89,440',
  '1,09,990',
  '18',
  '4.6'),
 ('walker Intel Celeron Dual Core Intel N4020',
  'walker',
  'Intel Core i3 Processor (13th Gen)',
  '4',
  '3',
  '3',
  '15,390',
  '30,000',
  '48',
  '4'),
 ('MICROSOFT Surface Laptop 13.8 Inch Snapdragon X2 Plus',
  'MICROSOFT',
  '8 GB LPDDR4X RAM',
  '32',
  '8',
  '8',
  '2,67,990',
  '2,69,999',
  '22',
  '3.9'),
 ('Acer One 14 AMD Ryzen 3 Quad Core 7320U',
  'Acer',
  '64 bit Windows 11 Operating System',
  '8',
  '64',
  '64',
  '37,990',
  '48,999',
  '15',
  '4.6'),
 ('Acer Aspire 3 Intel Pentium Quad Core N6000',
  'Acer',
  '512 GB SSD',
  '12',
  '512',
  '512',
  '39,938',
  '46,990',
  '17',
  '4.3'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
  'Samsung',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '62',
  '62',
  '82,951',
  '99,990',
  '5',
  '4.4'),
 ('Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H',
  'Lenovo',
  '1 Year Onsite Warranty',
  '16',
  '1',
  '1',
  '75,371',
  '79,900',
  '48',
  '4.4'),
 ('ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X',
  'ASUS',
  'AMD Ryzen 3 Quad Core Processor',
  '16',
  '3',
  '3',
  '58,990',
  '1,14,990',
  '29',
  '4'),
 ('MICROSOFT Surface Laptop 15 Inch Snapdragon X2 Elite',
  'MICROSOFT',
  '8 GB DDR4 RAM',
  '16',
  '8',
  '8',
  '2,09,990',
  '2,11,999',
  '17',
  '4.1'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'Samsung',
  '64 bit Windows 11 Home Operating System',
  '8',
  '64',
  '64',
  '55,311',
  '78,189',
  '33',
  '4.4'),
 ('Acer Aspire 7 (i7 14th Gen) Intel Core 7 240H',
  'Acer',
  '256 GB SSD',
  '16',
  '256',
  '256',
  '77,990',
  '94,999',
  '2',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  '39.62 cm (15.6 inch) Display',
  '32',
  '62',
  '62',
  '97,050',
  '1,46,990',
  '15',
  '4.3'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  'MSO',
  '16',
  '1',
  '1',
  '1,25,170',
  '1,27,990',
  '14',
  '4.3'),
 ('ASUS ROG Zephyrus G16 OLED (2026) Intel Core Ultra 9 386H',
  'ASUS',
  '1 Year Onsite Service',
  '32',
  '5',
  '5',
  '4,99,990',
  '5,93,990',
  '30',
  '4.3'),
 ('Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781)',
  'Primebook',
  'Intel Core 5 Processor',
  '8',
  '16',
  '16',
  '29,990',
  '34,990',
  '27',
  '4.1'),
 ('ASUS ExpertBook P1 Intel Core i7 13th Gen 13620H',
  'ASUS',
  '16 GB LPDDR5 RAM',
  '32',
  '64',
  '64',
  '89,990',
  '1,29,990',
  '27',
  '4.4'),
 ('ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U',
  'ASUS',
  '64 bit Windows 11 Home Operating System',
  '8',
  '512',
  '512',
  '50,990',
  '69,990',
  '7',
  '5'),
 ('MSI Modern 14 Intel Core i3 13th Gen 1315U',
  'MSI',
  '512 GB SSD',
  '8',
  '62',
  '62',
  '42,990',
  '58,990',
  '29',
  '4'),
 ('Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U',
  'Acer',
  '39.62 cm (15.6 inch) Display',
  '8',
  '1',
  '1',
  '48,104',
  '51,999',
  '17',
  '4'),
 ('Primebook 2 Pro (2025) in-Built AI MediaTek Helio G99 (MT8781)',
  'Primebook',
  '1 Year Onsite Service',
  '8',
  '3',
  '3',
  '26,990',
  '39,990',
  '15',
  '5'),
 ('ASUS ExpertBook P1 (i3 14th Gen) with 1 Yr ADP Intel Core 3 14th Gen 100U',
  'ASUS',
  'Intel Core i3 Processor (13th Gen)',
  '16',
  '8',
  '8',
  '58,990',
  '74,990',
  '2',
  '4'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'Samsung',
  '8 GB DDR5 RAM',
  '8',
  '11',
  '11',
  '55,311',
  '78,189',
  '33',
  '3.9'),
 ('Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
  'Samsung',
  'Windows 11 Home Operating System',
  '8',
  '512',
  '512',
  '51,990',
  '57,499',
  '32',
  '4'),
 ('Acer Aspire Lite AMD Ryzen 3 Quad Core 5300U',
  'Acer',
  '512 GB SSD',
  '16',
  '62',
  '62',
  '47,938',
  '49,990',
  '21',
  '1'),
 ('ASUS Vivobook 16 (2025) with Office 2024 + M365 Basic* Intel Core i5 13th Gen 13420H',
  'ASUS',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '2024',
  '2024',
  '64,990',
  '72,990',
  '29',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
  'Samsung',
  'Microsoft Office Home 2024 + Microsoft 365 Basic',
  '16',
  '1',
  '1',
  '82,951',
  '99,990',
  '9',
  '5'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  '1 Year Onsite Warranty',
  '16',
  '7',
  '7',
  '89,440',
  '1,09,990',
  '4',
  '5'),
 ('HP 14 AI PC Intel Core Ultra 7 155H',
  'HP',
  'Intel Core Ultra 7 Processor',
  '24',
  '16',
  '16',
  '92,990',
  '1,38,782',
  '10',
  '4.1'),
 ('ASUS Expertbook P3 Metal High-performance processor with 1 Yr ADP Intel Core i7 13th Gen 13620H',
  'ASUS',
  '16 GB LPDDR5X RAM',
  '32',
  '64',
  '64',
  '87,990',
  '1,19,990',
  '17',
  '3'),
 ('ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150',
  'ASUS',
  '64 bit Windows 11 Operating System',
  '16',
  '512',
  '512',
  '64,990',
  '1,11,990',
  '18',
  '3'),
 ('ASUS Vivobook Go 14 (2026) with Office 2024 + M365 Basic AMD Ryzen 3 Quad Core 30',
  'ASUS',
  '512 GB SSD',
  '8',
  '62',
  '62',
  '48,990',
  '72,990',
  '32',
  '4.4'),
 ('Acer Aspire 3 Intel Celeron Dual Core',
  'ASUS',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '1',
  '1',
  '66,980',
  '73,990',
  '26',
  '4.3'),
 ('Infinix Y3Plus Intel Core i3 13th Gen 1315U',
  'Acer',
  'MS Office Home and Student 2024',
  '8',
  '4',
  '4',
  '38,999',
  '43,999',
  '41',
  '4.4'),
 ('ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic*, Intel Core i3 13th Gen 1315U',
  'Infinix',
  '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
  '8',
  '32',
  '32',
  '39,990',
  '54,990',
  '32',
  '4.4'),
 ('ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Snapdragon X',
  'ASUS',
  'Intel Celeron Dual Core Processor',
  '8',
  '128',
  '128',
  '42,990',
  '50,990',
  '9',
  '4.1'),
 ('Lenovo Yoga Slim 7 WUXGA OLED with 1Yr ADP Intel Core Ultra 9 185H',
  'ASUS',
  '4 GB DDR4 RAM',
  '16',
  '56',
  '56',
  '58,990',
  '1,22,990',
  '11',
  '4.4'),
 ('ASUS Vivobook 15 Intel Core i3 12th Gen 1215U',
  'ASUS',
  '32 bit Windows 11 Operating System',
  '16',
  '1',
  '1',
  '65,990',
  '1,58,090',
  '27',
  '4.6'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'Lenovo',
  '128 GB SSD',
  '32',
  '2',
  '2',
  '1,10,990',
  '54,990',
  '15',
  '4.6'),
 ('HP Intel Core i3 13th Gen 1315U',
  'ASUS',
  '35.56 cm (14 inch) Display',
  '8',
  '32',
  '32',
  '35,990',
  '82,789',
  '52',
  '4.2'),
 ('ASUS Vivobook 15 (2025) with Office 2024 + M365 Basic*, Intel Core i3 13th Gen 1315U',
  'Samsung',
  '1 Year Onsite Service',
  '16',
  '64',
  '64',
  '71,251',
  '59,990',
  '29',
  '4.3'),
 ('Lenovo Chromebook 11IJL9 Intel Celeron Dual Core N4500',
  'HP',
  'Snapdragon X2 Plus Processor',
  '8',
  '512',
  '512',
  '50,900',
  '54,990',
  '34',
  '4.5'),
 ('HP G9 Intel Core i3 13th Gen 1315U',
  'ASUS',
  '32 GB LPDDR5X RAM',
  '16',
  '05',
  '05',
  '46,990',
  '31,423',
  '13',
  '4.3'),
 ('Infinix ZEROBOOK 13 Intel Intel Core i9 13th Gen 13900H',
  'Lenovo',
  '64 bit Windows 11 Operating System',
  '4',
  '1',
  '1',
  '15,999',
  '69,724',
  '15',
  '4.3'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'HP',
  '512 GB SSD',
  '16',
  '3',
  '3',
  '49,990',
  '1,23,990',
  '14',
  '3.8'),
 ('Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
  'Infinix',
  '35.05 cm (13.8 inch) Touchscreen Display',
  '32',
  '8',
  '8',
  '58,990',
  '78,189',
  '49',
  '4'),
 ('Lenovo IdeaPad Slim 1 AMD Ryzen 5 Hexa Core 5500U',
  'Samsung',
  'NA',
  '8',
  '64',
  '64',
  '55,311',
  '57,499',
  '9',
  '4.5'),
 ('HP Essentials(i5 14th Gen) Intel Core 5 13th Gen 120U',
  'Samsung',
  '1 Year Onsite Service',
  '8',
  '256',
  '256',
  '51,990',
  '83,000',
  '10',
  '4.4'),
 ('HP 15 (2025) AMD Ryzen 3 Quad Core 7320U',
  'Lenovo',
  'AMD Ryzen 3 Quad Core Processor',
  '16',
  '56',
  '56',
  '63,999',
  '72,053',
  '9',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'HP',
  '8 GB LPDDR5 RAM',
  '8',
  '1',
  '1',
  '62,990',
  '94,890',
  '49',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
  'Lenovo',
  '64 bit Windows 11 Operating System',
  '24',
  '12',
  '12',
  '89,990',
  '68,990',
  '18',
  '4.3'),
 ('ASUS Vivobook 14 (2025) with Office 2024 + M365 Basic*, Backlit Keyboard, Intel Core Ultra 5 225H',
  'HP',
  '256 GB SSD',
  '16',
  '11',
  '11',
  '61,541',
  '1,09,990',
  '28',
  '4.4'),
 ('ASUS Expertbook P1 with 1 Yr ADP(i3 14th Gen) Intel Core 3 13th Gen 1315U',
  'Samsung',
  '35.56 cm (14 Inch) Display',
  '16',
  '512',
  '512',
  '89,440',
  '99,990',
  '52',
  '4.1'),
 ('Acer Aspire Intel Core i5 12th Gen 12450H',
  'Samsung',
  '1 Year International Travelers Warranty (ITW)',
  '16',
  '62',
  '62',
  '82,951',
  '81,990',
  '29',
  '4.5'),
 ('ASUS ROG Strix G16 (2026) AMD Ryzen 9 16 Core 8940HX',
  'ASUS',
  'Intel Pentium Quad Core Processor',
  '16',
  '1',
  '1',
  '73,990',
  '69,990',
  '9',
  '4'),
 ('Lenovo Ideapad Slim 3 OLED with 1Yr ADP Snapdragon X',
  'ASUS',
  '12 GB LPDDR4X RAM',
  '8',
  '5',
  '5',
  '50,990',
  '63,990',
  '22',
  '4.3'),
 ('HP 15 G10 (2025) AMD Athlon Dual Core 7120U',
  'Acer',
  'Windows 11 Home Operating System',
  '12',
  '16',
  '16',
  '59,990',
  '2,43,990',
  '12',
  '5'),
 ('ASUS Chromebook CX14 Intel Celeron Dual Core N50',
  'ASUS',
  '512 GB SSD',
  '16',
  '64',
  '64',
  '1,59,990',
  '86,690',
  '5',
  '5'),
 ('ASUS Expertbook P3 Metal High-performance processor with 1 Yr ADP Intel Core i5 13th Gen 13420H',
  'Lenovo',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '512',
  '512',
  '71,990',
  '49,670',
  '10',
  '4.4'),
 ('Acer Predator Helios Neo 16S AI Intel Core Ultra 7 255HX',
  'HP',
  '1 Year International Travelers Warranty (ITW)',
  '8',
  '62',
  '62',
  '46,683',
  '95,990',
  '18',
  '5'),
 ('ASUS Vivobook 15 (2025) with Touchscreen & Backlit Keyboard, Intel Core i3 13th Gen 1315U',
  'ASUS',
  'Intel Core Ultra 5 Processor',
  '4',
  '1',
  '1',
  '22,990',
  '2,13,999',
  '17',
  '5'),
 ('HP 14 AI PC Intel Core Ultra 7 155H',
  'ASUS',
  '16 GB LPDDR5X RAM',
  '16',
  '5',
  '5',
  '67,990',
  '51,990',
  '9',
  '4.4'),
 ('HP Professional 14, Intel Core i5 13th Gen 1334U',
  'Acer',
  '64 bit Windows 11 Operating System',
  '16',
  '16',
  '16',
  '1,71,990',
  '99,990',
  '27',
  '5'),
 ('Acer Swift Neo Office 2024 + M365 Basic Intel Core Ultra 7 155U',
  'ASUS',
  '512 GB SSD',
  '8',
  '64',
  '64',
  '42,990',
  '84,990',
  '6',
  '5'),
 ('HP Victus(i5 14th Gen) Intel Core 5 210H',
  'HP',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '512',
  '512',
  '87,990',
  '97,999',
  '34',
  '4'),
 ('ASUS Vivobook 16 (2025) with Office 2024 + M365 Basic, AI PC Intel Core Ultra 5 Series 2 225H',
  'HP',
  'MS Office Home and Student 2024',
  '16',
  '62',
  '62',
  '78,480',
  '1,47,674',
  '16',
  '5'),
 ('ASUS Vivobook Go 15 (2026) with Office 2024 + M365 Basic* AMD Ryzen 3 Quad Core 30',
  'Acer',
  '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
  '16',
  '1',
  '1',
  '65,990',
  '92,990',
  '6',
  '1'),
 ('HP Victus AMD Ryzen 7 Hexa Core 7445HS',
  'HP',
  'Intel Core i5 Processor (13th Gen)',
  '24',
  '16',
  '16',
  '93,990',
  '78,189',
  '29',
  '4.6'),
 ('Acer Aspire AMD Ryzen 5 Hexa Core 7430U',
  'ASUS',
  '16 GB LPDDR5 RAM',
  '16',
  '11',
  '11',
  '73,990',
  '57,499',
  '19',
  '5'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'ASUS',
  '64 bit Windows 11 Operating System',
  '8',
  '512',
  '512',
  '48,990',
  '53,999',
  '17',
  '5'),
 ('Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
  'HP',
  '512 GB SSD',
  '16',
  '56',
  '56',
  '76,354',
  '44,990',
  '12',
  '4'),
 ('Acer Aspire 15 AMD Ryzen 3 Quad Core 7330U',
  'Acer',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '2024',
  '2024',
  '59,990',
  '99,990',
  '7',
  '4'),
 ('Acer Aspire Lite AMD Ryzen 3 Quad Core 5300U',
  'Samsung',
  '1 Yr. Onsite + 1 Yr. Accidental Damage Protection',
  '8',
  '1',
  '1',
  '55,311',
  '1,09,990',
  '32',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
  'Samsung',
  'Snapdragon X Processor',
  '8',
  '2',
  '2',
  '51,990',
  '1,45,000',
  '36',
  '4.4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Acer',
  '16 GB LPDDR5X RAM',
  '8',
  '16',
  '16',
  '44,990',
  '37,690',
  '29',
  '4.2'),
 ('MOTOROLA Motobook 60 Pro Full Metal AI PC WUXGA OLED Intel Core Ultra 5 225H',
  'Acer',
  'Windows 11 Home Operating System',
  '8',
  '64',
  '64',
  '42,990',
  '79,900',
  '52',
  '4.5'),
 ('Lenovo IdeaPad Slim 1 AMD Ryzen 5 Hexa Core 5500U',
  'Samsung',
  '512 GB SSD',
  '16',
  '512',
  '512',
  '82,951',
  '1,46,990',
  '36',
  '4.4'),
 ('HP 15 (2024) AMD Ryzen 3 Quad Core 7320U',
  'Samsung',
  '35.56 cm (14 Inch) Display',
  '16',
  '1',
  '1',
  '89,440',
  '89,689',
  '29',
  '4'),
 ('Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838',
  'MOTOROLA',
  'Microsoft Office Home 2024 (Lifetime Validity ) + Microsoft 365 Basic*(1-Year Validity), One-Month Membership of Adobe Creative Cloud All Apps',
  '16',
  '1',
  '1',
  '79,990',
  '99,990',
  '32',
  '4.6'),
 ('Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H',
  'Lenovo',
  '1 Year Onsite Warranty',
  '8',
  '5',
  '5',
  '47,290',
  '1,27,990',
  '20',
  '4.6'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'HP',
  'Snapdragon X2 Elite Processor',
  '8',
  '8',
  '8',
  '44,783',
  '78,778',
  '29',
  '4.4'),
 ('Samsung Galaxy Book4 Metal Intel Core i7 13th Gen 1355U',
  'Lenovo',
  '16 GB LPDDR5X RAM',
  '8',
  '64',
  '64',
  '36,990',
  '92,990',
  '9',
  '4.3'),
 ('ASUS V16 (2025) for Creator with Office 2024 + M365 Basic*,AI PC (i5 14th Gen) Intel Core 5 210H',
  'Lenovo',
  '64 bit Windows 11 Operating System',
  '16',
  '512',
  '512',
  '75,371',
  '59,990',
  '16',
  '4.1'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  '512 GB SSD',
  '32',
  '62',
  '62',
  '97,050',
  '83,632',
  '4',
  '4.3'),
 ('HP OmniBook 5(Previously Pavilion) Intel Core i5 13th Gen 1334U',
  'Samsung',
  '38.1 cm (15 inch) Touchscreen Display',
  '16',
  '1',
  '1',
  '78,091',
  '78,189',
  '17',
  '4.7'),
 ('DELL Inspiron Intel Core i3 6th Gen 6100U',
  'ASUS',
  'NA',
  '16',
  '7',
  '7',
  '92,990',
  '57,499',
  '18',
  '4'),
 ('ASUS Vivobook S14 (2025) with Office 2024 + M365 Basic*, AI PC, Backlit Keyboard, Snapdragon X',
  'Samsung',
  '1 Year Onsite Service',
  '16',
  '16',
  '16',
  '1,25,170',
  '69,990',
  '44',
  '3.8'),
 ('ASUS Vivobook 15, with Backlit Keyboard, Intel Core i3 13th Gen 1315U',
  'HP',
  'Intel Core i5 Processor (13th Gen)',
  '16',
  '64',
  '64',
  '71,990',
  '39,990',
  '1',
  '4.4'),
 ('ASUS Vivobook 15 (2026) with Office 2024 + M365 Basic*, AMD Ryzen 5 Hexa Core 150',
  'DELL',
  '8 GB LPDDR4X RAM',
  '4',
  '512',
  '512',
  '35,848',
  '99,990',
  '5',
  '4.4'),
 ('Samsung Galaxy Book4 Metal Intel Core i5 13th Gen 1335U',
  'ASUS',
  '64 bit Windows 11 Operating System',
  '16',
  '62',
  '62',
  '65,990',
  '1,09,990',
  '33',
  '4.3'),
 ('Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U',
  'ASUS',
  '512 GB SSD',
  '16',
  '1',
  '1',
  '57,626',
  '69,999',
  '12',
  '4.2'),
 ('ASUS Vivobook 15 Intel Core i5 12th Gen 1235U',
  'ASUS',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '7',
  '7',
  '64,990',
  '53,327',
  '7',
  '4.5'),
 ('Acer Aspire 3 Intel Celeron Dual Core',
  'Samsung',
  '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
  '8',
  '32',
  '32',
  '55,311',
  '84,990',
  '2',
  '4.1'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 5 225U',
  'Samsung',
  'Intel Core 7 Processor',
  '8',
  '64',
  '64',
  '51,990',
  '43,000',
  '8',
  '4.2'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'ASUS',
  '16 GB DDR4 RAM',
  '8',
  '1',
  '1',
  '39,990',
  '79,900',
  '29',
  '4.4'),
 ('Acer Aspire 15 AMD Ryzen 5 Hexa Core 7430U',
  'Acer',
  '64 bit Windows 11 Home Operating System',
  '8',
  '62',
  '62',
  '32,900',
  '1,46,990',
  '3',
  '5'),
 ('HP 15s Metal Intel Core i3 13th Gen 1315U',
  'Samsung',
  '512 GB SSD',
  '16',
  '1',
  '1',
  '82,951',
  '85,000',
  '22',
  '4'),
 ('Acer Swift Lite 14 Intel Core Ultra 5 115U',
  'Samsung',
  '39.62 cm (15.6 Inch) Display',
  '16',
  '7',
  '7',
  '89,440',
  '91,990',
  '29',
  '4'),
 ('Acer Aspire 3 Intel Core i3 12th Gen 1215U',
  'Acer',
  '1 Year Warranty',
  '8',
  '16',
  '16',
  '55,990',
  '1,27,990',
  '4',
  '3'),
 ('Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 13420H',
  'HP',
  'Intel Core Ultra 7 Processor',
  '8',
  '64',
  '64',
  '49,990',
  '87,990',
  '2',
  '1'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Acer',
  '32 GB LPDDR5X RAM',
  '16',
  '1',
  '1',
  '69,645',
  '69,695',
  '29',
  '4.2'),
 ('Lenovo IdeaPad Slim 3 WUXGA IPS Intel Core i5 13th Gen 13420H',
  'Acer',
  '64 bit Windows 11 Operating System',
  '8',
  '62',
  '62',
  '25,990',
  '1,14,990',
  '9',
  '5'),
 ('ASUS TUF Gaming F16 (2025) with MSO 2024+M365 Basic (i5 14th Gen) Intel Core 5',
  'Lenovo',
  '1 TB SSD',
  '16',
  '1',
  '1',
  '75,371',
  '1,14,999',
  '42',
  '4'),
 ('Samsung Galaxy Book5 AI Metal Intel Core Ultra 7 255U',
  'Samsung',
  '39.62 cm (15.6 Inch) Display',
  '32',
  '9',
  '9',
  '97,050',
  '1,16,990',
  '17',
  '4.4'),
 ("Lenovo IdeaPad Slim 3 Backlit Keyboard with MSO'2024 Intel Core i5 13th Gen 13420H",
  'Lenovo',
  'MS Office Home and Student 2024',
  '16',
  '32',
  '32',
  '74,999',
  '1,92,990',
  '17',
  '5'),
 ('DELL 15 (Previously Inspiron) (2025) Microsoft Office Home 2024 AMD Ryzen 5 Hexa Core 7530U',
  'ASUS',
  '1 Year Manufacturer Warranty for Laptop and 6 Months for In-Box Accessories',
  '16',
  '11',
  '11',
  '79,990',
  '73,990',
  '18',
  '5'),
 ('ASUS Expertbook P1 with 1 Yr ADP (i5 14th Gen) Intel Core 5 210H',
  'Samsung',
  'Intel Core Ultra 7 Processor',
  '16',
  '2',
  '2',
  '1,25,170',
  '69,990',
  '20',
  '4.1'),
 ('Acer Nitro V 15 Intel Core i5 13th Gen 13420H',
  'ASUS',
  '16 GB LPDDR5X RAM',
  '8',
  '64',
  '64',
  '50,990',
  '78,189',
  '6',
  '3'),
 ('ASUS Vivobook 16 (2025) with MSO 2024 + M365 Basic* AMD Ryzen 5 Hexa Core',
  'Lenovo',
  '64 bit Windows 11 Operating System',
  '24',
  '2024',
  '2024',
  '79,990',
  '57,499',
  '18',
  '3'),
 ('ASUS ExpertBook P3 Intel Core Ultra 7 255H',
  'DELL',
  '1 TB SSD',
  '16',
  '1',
  '1',
  '59,990',
  '95,990',
  '39',
  '4.3'),
 ('ASUS Vivobook 15 (2025)(i5 14th Gen)with MSO 2024 + M365 Basic, Backlit Keyboard, Intel Core 5 120U',
  'ASUS',
  '39.62 cm (15.6 Inch) Display',
  '32',
  '99',
  '99',
  '80,878',
  '54,990',
  '5',
  '4.1'),
 ('Acer Aspire Lite Intel Core i5 12th Gen 12450H',
  'Acer',
  'MS Office Home and Student 2024',
  '16',
  '8',
  '8',

In [52]:
df=pd.DataFrame(data,columns=['Brand','Brand_title','Processor','RAM','SSD','Display','Price','original_price','Discount','Ratings'])
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8,5,5,"55,311","78,189",29,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8,8,8,"51,990","57,499",9,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8,64,64,"39,990","74,999",46,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16,512,512,"59,990","78,999",24,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8,62,62,"42,990","50,990",15,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,None,None,16 GB DDR4 RAM,None,None,None,None,None,None,None
1569,None,None,Windows 11 Operating System,None,None,None,None,None,None,None
1570,None,None,512 GB SSD,None,None,None,None,None,None,None
1571,None,None,39.62 cm (15.6 Inch) Display,None,None,None,None,None,None,None
1572,None,None,1 Year Carry-in Warranty,None,None,None,None,None,None,None

In [53]:
df.to_csv("laptop.csv")

In [54]:
df.shape

(1573, 10)

In [55]:
df.head(10)

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8,5,5,"55,311","78,189",29,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8,8,8,"51,990","57,499",9,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8,64,64,"39,990","74,999",46,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16,512,512,"59,990","78,999",24,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8,62,62,"42,990","50,990",15,4.3
5,Samsung Galaxy Book5 AI Metal Intel Core Ultra...,Samsung,1 Year Manufacturer Warranty for Laptop and 6 ...,16,1,1,"89,440","1,09,990",18,4.6
6,walker Intel Celeron Dual Core Intel N4020,walker,Intel Core i3 Processor (13th Gen),4,3,3,"15,390","30,000",48,4
7,MICROSOFT Surface Laptop 13.8 Inch Snapdragon ...,MICROSOFT,8 GB LPDDR4X RAM,32,8,8,"2,67,990","2,69,999",22,3.9
8,Acer One 14 AMD Ryzen 3 Quad Core 7320U,Acer,64 bit Windows 11 Operating System,8,64,64,"37,990","48,999",15,4.6
9,Acer Aspire 3 Intel Pentium Quad Core N6000,Acer,512 GB SSD,12,512,512,"39,938","46,990",17,4.3

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           234 non-null    object
 1   Brand_title     240 non-null    object
 2   Processor       1573 non-null   object
 3   RAM             240 non-null    object
 4   SSD             1482 non-null   object
 5   Display         1482 non-null   object
 6   Price           240 non-null    object
 7   original_price  221 non-null    object
 8   Discount        261 non-null    object
 9   Ratings         376 non-null    object
dtypes: object(10)
memory usage: 123.0+ KB

In [57]:
df["Price"] = df["Price"].str.replace(",","")
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8,5,5,55311,"78,189",29,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8,8,8,51990,"57,499",9,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8,64,64,39990,"74,999",46,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16,512,512,59990,"78,999",24,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8,62,62,42990,"50,990",15,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,None,None,16 GB DDR4 RAM,None,None,None,None,None,None,None
1569,None,None,Windows 11 Operating System,None,None,None,None,None,None,None
1570,None,None,512 GB SSD,None,None,None,None,None,None,None
1571,None,None,39.62 cm (15.6 Inch) Display,None,None,None,None,None,None,None
1572,None,None,1 Year Carry-in Warranty,None,None,None,None,None,None,None

In [58]:
df["Price"] = df["Price"].astype("float64")
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8,5,5,55311.0,"78,189",29,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8,8,8,51990.0,"57,499",9,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8,64,64,39990.0,"74,999",46,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16,512,512,59990.0,"78,999",24,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8,62,62,42990.0,"50,990",15,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,None,None,16 GB DDR4 RAM,None,None,None,NaN,None,None,None
1569,None,None,Windows 11 Operating System,None,None,None,NaN,None,None,None
1570,None,None,512 GB SSD,None,None,None,NaN,None,None,None
1571,None,None,39.62 cm (15.6 Inch) Display,None,None,None,NaN,None,None,None
1572,None,None,1 Year Carry-in Warranty,None,None,None,NaN,None,None,None

In [63]:
df["Brand"] = df["Brand"].astype("string") 
df["Brand_title"] = df["Brand_title"].astype("string") 
df["Processor"] = df["Processor"].astype("string") 
df["RAM"] = df["RAM"].astype("float64") 
df["SSD"] = df["SSD"].astype("float64") 
df["Display"] = df["Display"].astype("float64") 
df["Price"] = df["Price"].astype("float64") 
#df["original_price"] = df["original_price"].astype("float64")
df["Discount"] = df["Discount"].astype("float64") 
df["Ratings"] = df["Ratings"].astype("float64") 
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8.0,5.0,5.0,55311.0,78189.0,29.0,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8.0,8.0,8.0,51990.0,57499.0,9.0,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8.0,64.0,64.0,39990.0,74999.0,46.0,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16.0,512.0,512.0,59990.0,78999.0,24.0,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8.0,62.0,62.0,42990.0,50990.0,15.0,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,<NA>,<NA>,16 GB DDR4 RAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1569,<NA>,<NA>,Windows 11 Operating System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,<NA>,<NA>,512 GB SSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1571,<NA>,<NA>,39.62 cm (15.6 Inch) Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1572,<NA>,<NA>,1 Year Carry-in Warranty,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df["original_price"] = df["original_price"].str.replace(",","")
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8.0,5.0,5.0,55311.0,78189,29,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8.0,8.0,8.0,51990.0,57499,9,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8.0,64.0,64.0,39990.0,74999,46,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16.0,512.0,512.0,59990.0,78999,24,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8.0,62.0,62.0,42990.0,50990,15,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,<NA>,<NA>,16 GB DDR4 RAM,NaN,NaN,NaN,NaN,None,None,None
1569,<NA>,<NA>,Windows 11 Operating System,NaN,NaN,NaN,NaN,None,None,None
1570,<NA>,<NA>,512 GB SSD,NaN,NaN,NaN,NaN,None,None,None
1571,<NA>,<NA>,39.62 cm (15.6 Inch) Display,NaN,NaN,NaN,NaN,None,None,None
1572,<NA>,<NA>,1 Year Carry-in Warranty,NaN,NaN,NaN,NaN,None,None,None

In [64]:
df["original_price"] = df["original_price"].astype("float64")
df

,Brand,Brand_title,Processor,RAM,SSD,Display,Price,original_price,Discount,Ratings
0,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Samsung,Intel Core i5 Processor (13th Gen),8.0,5.0,5.0,55311.0,78189.0,29.0,4.4
1,Samsung Galaxy Book4 Metal Intel Core i3 13th ...,Samsung,8 GB LPDDR4X RAM,8.0,8.0,8.0,51990.0,57499.0,9.0,4.4
2,"Acer Aspire 15 MS Office 2024 + M365 Basic, AM...",Acer,64 bit Windows 11 Operating System,8.0,64.0,64.0,39990.0,74999.0,46.0,3.7
3,Acer Aspire 15 Lite(i5 14th Gen) Intel Core 5 ...,Acer,512 GB SSD,16.0,512.0,512.0,59990.0,78999.0,24.0,4.5
4,ASUS Vivobook 15 (2025) with Office 2024 + M36...,ASUS,39.62 cm (15.6 Inch) Display,8.0,62.0,62.0,42990.0,50990.0,15.0,4.3
...,...,...,...,...,...,...,...,...,...,...
1568,<NA>,<NA>,16 GB DDR4 RAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1569,<NA>,<NA>,Windows 11 Operating System,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1570,<NA>,<NA>,512 GB SSD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1571,<NA>,<NA>,39.62 cm (15.6 Inch) Display,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1572,<NA>,<NA>,1 Year Carry-in Warranty,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           234 non-null    string
 1   Brand_title     240 non-null    string
 2   Processor       1573 non-null   string
 3   RAM             240 non-null    float64
 4   SSD             1482 non-null   float64
 5   Display         1482 non-null   float64
 6   Price           240 non-null    float64
 7   original_price  221 non-null    float64
 8   Discount        261 non-null    float64
 9   Ratings         376 non-null    float64
dtypes: float64(7), string(3)
memory usage: 123.0 KB